default_language_version:
  python: python3.9


repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: 'v5.9.3'
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
      - id: black
        args: [--line-length, "120", "."]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-builtin-literals
      - id: check-docstring-first
      - id: flake8
        args: [
            "--max-line-length=200",
        ]

  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-check-blanket-noqa

  - repo: https://github.com/asottile/blacken-docs
    rev: v1.11.0
    hooks:
      - id: blacken-docs

  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: "v1.2.2"
    hooks:
      - id: python-safety-dependencies-check
