[mypy]
plugins = pydantic.mypy,
          returns.contrib.mypy.returns_plugin,
          lambdas.contrib.mypy.lambdas_plugin
mypy_path=.
follow_imports = normal
incremental = True
warn_redundant_casts = True
strict_optional = True
strict_equality = True
warn_unused_configs = True
warn_return_any = True
warn_unused_ignores = True
disallow_untyped_defs = True
disallow_any_generics = True
allow_redefinition = false
check_untyped_defs = True
implicit_reexport = True
local_partial_types = True
no_implicit_optional = True
warn_unreachable = True
;
;[mypy-homies.migrations.*]
;disallow_untyped_defs = False
;ignore_errors = True
;
;# Ignoring imports from libraries that doesn't support mypy individually
;# to avoid setting `ignore_missing_imports` globally. Libs should be listed here only
;# if they are not typed; if they are, they should be added to `additional_dependencies`
;# in `mypy` hook configuration in `.pre-commit-config.yml` file
;[mypy-factory.*]
;ignore_missing_imports = True
;
;[mypy-dependencies.*]
;ignore_missing_imports = True
;
;[mypy-fastapi_login.*]
;ignore_missing_imports = True
;
;[mypy-pytest_factoryboy.*]
;ignore_missing_imports = True
;
;[mypy-fastapi_camelcase.*]
;ignore_missing_imports = True
;
;[mypy-alembic.*]
;ignore_missing_imports = True
;
;[mypy-envparse.*]
;ignore_missing_imports = True
;
;[mypy-passlib.*]
;ignore_missing_imports = True
;
;[mypy-sentry_sdk.*]
;ignore_missing_imports = True
;
;[mypy-boto3.*]
;ignore_missing_imports = True
;
;[mypy-boto3_type_annotations.*]
;ignore_missing_imports = True
;
;[mypy-botocore.*]
;ignore_missing_imports = True
;
;[mypy-moto.*]
;ignore_missing_imports = True
